/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClasesBases.Idioma;
import ClasesBases.Interes;
import ClasesBases.Usuario;
import java.util.ArrayList;

/**
 *
 * @author ivanm
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    ArrayList<Idioma> idiomas = new ArrayList<>();
    ArrayList<Interes> intereses = new ArrayList<>();

    public VentanaLogin() {
        initComponents();
        setTitle("ChatLearning");

        idiomas.add(new Idioma(idiomas.size(), "Inglés"));
        idiomas.add(new Idioma(idiomas.size(), "Español"));
        idiomas.add(new Idioma(idiomas.size(), "Japonés"));
        idiomas.add(new Idioma(idiomas.size(), "Italiano"));
        idiomas.add(new Idioma(idiomas.size(), "Ruso"));
        idiomas.add(new Idioma(idiomas.size(), "Francés"));

        intereses.add(new Interes(intereses.size(), "Tecnología"));
        intereses.add(new Interes(intereses.size(), "Deportes"));
        intereses.add(new Interes(intereses.size(), "Política"));
        intereses.add(new Interes(intereses.size(), "Religión"));
        intereses.add(new Interes(intereses.size(), "Turismo"));

        cb_idmaterno.addItem("Selecciona..");
        cb_idpreferido.addItem("Selecciona..");
        cb_interes.addItem("Selecciona..");

        for (Idioma i : idiomas) {
            cb_idmaterno.addItem(i.getNombreIdioma());
            cb_idpreferido.addItem(i.getNombreIdioma());
        }
        for (Interes i : intereses) {
            cb_interes.addItem(i.getNombreInteres());
        }

        lb_msj_error.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_nombre = new javax.swing.JTextField();
        cb_idmaterno = new javax.swing.JComboBox<>();
        cb_interes = new javax.swing.JComboBox<>();
        cb_idpreferido = new javax.swing.JComboBox<>();
        bt_empezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_msj_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        bt_empezar.setText("Empezar");
        bt_empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_empezarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Idioma materno");

        jLabel3.setText("Idioma preferido");

        jLabel4.setText("Escoja un tema de interés");

        jLabel5.setText("Login");

        lb_msj_error.setText("Error!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombre)
                    .addComponent(cb_idmaterno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_idpreferido, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_interes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_msj_error))
                    .addComponent(bt_empezar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(cb_idmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(cb_idpreferido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_empezar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_msj_error)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void bt_empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_empezarActionPerformed
        empezar();
    }//GEN-LAST:event_bt_empezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    private void empezar() {
        if (verificar()) {
            Usuario u = new Usuario(0, tf_nombre.getText(),
                    cb_idmaterno.getSelectedIndex() + 1,
                    cb_idpreferido.getSelectedIndex() + 1,
                    cb_interes.getSelectedIndex() + 1);

            new VentanaPrincipal(u, idiomas, intereses).setVisible(true);
            this.setVisible(false);
        }
    }

    private boolean verificar() {
        boolean flag = true;
        if (tf_nombre.getText().length() == 0) {
            flag = false;
            lb_msj_error.setText("Falta el nombre.");
        } else {
            int id_materno = cb_idmaterno.getSelectedIndex();
            if (id_materno == 0) {
                flag = false;
                lb_msj_error.setText("Falta el idioma materno.");
            } else {
                int id_preferido = cb_idpreferido.getSelectedIndex();
                if (id_preferido == 0) {
                    flag = false;
                    lb_msj_error.setText("Falta el idioma preferido.");
                } else {
                    int id_interes = cb_interes.getSelectedIndex();
                    if (id_interes == 0) {
                        flag = false;
                        lb_msj_error.setText("Falta el interés.");
                    }
                }
            }
        }

        if (!flag) {
            lb_msj_error.setVisible(true);
        }

        return flag;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_empezar;
    private javax.swing.JComboBox<String> cb_idmaterno;
    private javax.swing.JComboBox<String> cb_idpreferido;
    private javax.swing.JComboBox<String> cb_interes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_msj_error;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
