/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClasesBases.Idioma;
import ClasesBases.Interes;
import ClasesBases.Usuario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author ivanm
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    Usuario usuarioLogueado;
    ArrayList<Idioma> idiomas = new ArrayList<>();
    ArrayList<Interes> intereses = new ArrayList<>();
    ArrayList<Usuario> usuarios = new ArrayList<>();
    ArrayList<Usuario> usuarios_filtrados = new ArrayList<>();
    JFrame thisFrame;

    public VentanaPrincipal(Usuario u, ArrayList<Idioma> lista_idiomas,
            ArrayList<Interes> lista_intereses) {
        initComponents();
        setTitle("ChatLearning");

        thisFrame = this;
        usuarios_filtrados = usuarios;
        usuarioLogueado = u;
        idiomas = lista_idiomas;
        intereses = lista_intereses;

        usuarios.add(new Usuario(usuarios.size(), "María", 0, 1, 3,
                new ArrayList<>(Arrays.asList(5, 2, 5, 1, 3, 2))));
        usuarios.add(new Usuario(usuarios.size(), "Carlos", 1, 2, 0,
                new ArrayList<>(Arrays.asList(3, 4, 1, 2, 3, 2))));
        usuarios.add(new Usuario(usuarios.size(), "Luis", 3, 0, 4,
                new ArrayList<>(Arrays.asList(5, 3, 4, 5, 5, 4))));
        usuarios.add(new Usuario(usuarios.size(), "Iván", 5, 3, 1,
                new ArrayList<>(Arrays.asList(2, 2, 3, 1, 4, 5))));
        usuarios.add(new Usuario(usuarios.size(), "David", 2, 4, 2,
                new ArrayList<>(Arrays.asList(4, 5, 5, 2, 3, 1))));
        usuarios.add(new Usuario(usuarios.size(), "Pedro", 4, 5, 3,
                new ArrayList<>(Arrays.asList(3, 4, 3, 5, 4, 5))));
        usuarios.add(new Usuario(usuarios.size(), "Camila", 1, 3, 4,
                new ArrayList<>(Arrays.asList(5, 3, 2, 5, 5, 4))));
        usuarios.add(new Usuario(usuarios.size(), "Karen", 2, 2, 1,
                new ArrayList<>(Arrays.asList(2, 5, 4, 2, 3, 5))));

        cb_idioma.addItem("Todos");
        cb_interes.addItem("Todos");
        for (Idioma i : idiomas) {
            cb_idioma.addItem(i.getNombreIdioma());
        }
        for (Interes i : intereses) {
            cb_interes.addItem(i.getNombreInteres());
        }

        cb_puntaje.addItem("Todos");
        cb_puntaje.addItem(">=1");
        cb_puntaje.addItem(">=2");
        cb_puntaje.addItem(">=3");
        cb_puntaje.addItem(">=4");

        lb_usuario.setText("Bienvenido " + usuarioLogueado.getNombre() + "!!");
        cargarUsuarios(usuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_puntaje = new javax.swing.JComboBox<>();
        cb_idioma = new javax.swing.JComboBox<>();
        cb_interes = new javax.swing.JComboBox<>();
        bt_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_usuarios = new javax.swing.JList<>();
        lb_usuario = new javax.swing.JLabel();
        bt_miperfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Puntuación");

        jLabel2.setText("Idioma");

        jLabel3.setText("Interés");

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_buscar)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bt_buscar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(list_usuarios);

        lb_usuario.setText("Bienvenido Usuario!");

        bt_miperfil.setText("Mi perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lb_usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bt_miperfil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_miperfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        filtrar();
    }//GEN-LAST:event_bt_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public void filtrar() {
        int id_puntuacion = cb_puntaje.getSelectedIndex();
        int id_idioma = cb_idioma.getSelectedIndex();
        int id_interes = cb_interes.getSelectedIndex();
        usuarios_filtrados = usuarios;
        ArrayList<Usuario> filtro_aux = new ArrayList<>();
        if (id_puntuacion > 0) {
            for (Usuario u : usuarios_filtrados) {
                if (u.getPuntaje() >= id_puntuacion) {
                    filtro_aux.add(u);
                }
            }
            usuarios_filtrados = filtro_aux;
        }
        filtro_aux = new ArrayList<>();
        if (id_idioma > 0) {
            for (Usuario u : usuarios_filtrados) {
                if (u.getIdIdiomaMaterno() == id_idioma - 1) {
                    filtro_aux.add(u);
                }
            }
            usuarios_filtrados = filtro_aux;
        }
        filtro_aux = new ArrayList<>();
        if (id_interes > 0) {
            for (Usuario u : usuarios_filtrados) {
                if (u.getIdInteres() == id_interes - 1) {
                    filtro_aux.add(u);
                }
            }
            usuarios_filtrados = filtro_aux;
        }
        cargarUsuarios(usuarios_filtrados);
    }

    private void cargarUsuarios(ArrayList<Usuario> listUsuario) {
        DefaultListModel model = new DefaultListModel();
        DecimalFormat df = new DecimalFormat("#.0");
        for (Usuario usu : listUsuario) {
            model.addElement(usu.getNombre() + " - "
                    + idiomas.get(usu.getIdIdiomaMaterno()).getNombreIdioma() + " - "
                    + intereses.get(usu.getIdInteres()).getNombreInteres() + " - "
                    + df.format(usu.getPuntaje()));
        }
        list_usuarios.setModel(model);
        list_usuarios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList) evt.getSource();
                if (evt.getClickCount() == 2) {

                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    Usuario uamigo = usuarios_filtrados.get(index);
                    new VentanaChat(usuarioLogueado, uamigo).setVisible(true);
//                    thisFrame.setVisible(false);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_miperfil;
    private javax.swing.JComboBox<String> cb_idioma;
    private javax.swing.JComboBox<String> cb_interes;
    private javax.swing.JComboBox<String> cb_puntaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JList<String> list_usuarios;
    // End of variables declaration//GEN-END:variables
}
